# Generated by Django 2.2.6 on 2019-10-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.Condominio')),
            ],
            options={
                'db_table': 'bloco',
            },
        ),
    ]
