# Generated by Django 2.2.6 on 2019-10-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'condominio',
            },
        ),
    ]
