# Generated by Django 2.2.7 on 2019-11-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('data_inicio_moradia', models.DateField()),
                ('data_fim_moradia', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartamento.Apartamento')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
