# Generated by Django 2.2.6 on 2019-11-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_apartamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_fim_moradia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_inicio_moradia',
            field=models.CharField(max_length=10),
        ),
    ]
