# Generated by Django 2.2.6 on 2019-11-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191103_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_fim_moradia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
