# Generated by Django 2.2.6 on 2019-11-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191104_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_fim_moradia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_inicio_moradia',
            field=models.DateField(),
        ),
    ]
