# Generated by Django 2.2.4 on 2019-11-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leitor', '0002_auto_20191110_2001'),
        ('apartamento', '0002_auto_20191103_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leitura', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data_leitura', models.DateField()),
                ('periodo_leitura', models.IntegerField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=11)),
                ('valor_gas', models.DecimalField(decimal_places=2, max_digits=11)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=11)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartamento.Apartamento')),
                ('consumo_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumo_anterior_set', to='consumo.Consumo')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leitor.Leitor')),
            ],
            options={
                'db_table': 'consumo',
            },
        ),
    ]
