# Generated by Django 2.2.4 on 2019-11-12 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='consumo_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumo_anterior_set', to='consumo.Consumo'),
        ),
    ]
