# Generated by Django 2.2.7 on 2019-11-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0002_auto_20191112_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='gas',
        ),
        migrations.AddField(
            model_name='consumo',
            name='valor_gas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
