# Generated by Django 2.2.7 on 2019-11-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('esta_disponivel', models.BooleanField(default=False)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloco.Bloco')),
            ],
            options={
                'db_table': 'apartamento',
            },
        ),
    ]
