# Generated by Django 2.2.6 on 2019-10-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloco', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'apartamento',
            },
        ),
    ]
