# Generated by Django 2.2.6 on 2019-11-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartamento', '0001_initial'),
        ('bloco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='esta_disponivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloco.Bloco'),
        ),
    ]
