# Generated by Django 2.2.6 on 2019-11-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data fim moradia.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_inicio',
            field=models.DateField(verbose_name='data inicio moradia.'),
        ),
    ]
