# Generated by Django 2.2.6 on 2019-11-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191126_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='data inicio moradia.'),
        ),
    ]
