# Generated by Django 2.2.6 on 2019-11-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191126_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(help_text='Requer. 14 characteres considerando as pontoaçoes. Exemplo xxx.xxx.xxx-xx', max_length=15, unique=True, verbose_name='CPF'),
        ),
    ]
