# Generated by Django 2.2.7 on 2019-11-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'leitor',
            },
        ),
    ]
