# Generated by Django 2.2.6 on 2019-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
